# SPDX-FileCopyrightText: 2023 Aleksandr Mezin <mezin.alexander@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

on:
  workflow_dispatch:
  workflow_call:

env:
  FORCE_COLOR: 1

defaults:
  run:
    shell: bash

jobs:
  configure:
    runs-on: ubuntu-24.04

    outputs:
      linguas: ${{ steps.generate.outputs.linguas }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate locale list
        id: generate
        run: |
          echo -n linguas= >>$GITHUB_OUTPUT
          grep -Ev '^\s*#.*' LINGUAS | jq -Rcn '[inputs | scan("\\S+")]' >>$GITHUB_OUTPUT
        shell: bash
        working-directory: locale

  check:
    needs: configure

    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/ddterm/ci-docker-image:2024.11.17.0

    strategy:
      fail-fast: false
      matrix:
        lang: ${{ fromJson(needs.configure.outputs.linguas) }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - run: git config --global --replace-all safe.directory "$GITHUB_WORKSPACE"

    - name: Enable generic problem matcher
      run: echo "::add-matcher::.github/problem-matchers/generic.json"

    - name: Enable gettext stats problem matcher
      run: echo "::add-matcher::.github/problem-matchers/gettext-stats.json"

    - name: Compile translation
      run: |
        echo locale/${{ matrix.lang }}.po
        msgfmt --check -v -o /dev/null locale/${{ matrix.lang }}.po 2>&1 | tee $GITHUB_STEP_SUMMARY
      shell: bash

    - name: Disable gettext stats problem matcher
      run: echo "::remove-matcher owner=gettext-stats::"

    - name: Ensure .po file is in sync with .pot
      run: msgcmp --use-untranslated --use-fuzzy locale/${{ matrix.lang }}.po locale/*.pot
      shell: bash
      if: ${{ always() && steps.meson-setup.conclusion == 'success' }}
