on:
  workflow_dispatch:
  workflow_call:

env:
  FORCE_COLOR: 1
  PIP_DISABLE_PIP_VERSION_CHECK: 1

jobs:
  configure:
    runs-on: ubuntu-latest

    outputs:
      linguas: ${{ steps.generate.outputs.linguas }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate locale list
        id: generate
        run: |
          echo -n linguas= >>$GITHUB_OUTPUT
          awk '/^\s*[^#]/ {$1=$1; print}' LINGUAS | jq -Rcn '[inputs | split(" ")] | flatten' >>$GITHUB_OUTPUT
        shell: bash
        working-directory: po

  check:
    needs: configure

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ddterm/ci-docker-image:2023.11.28.0

    strategy:
      fail-fast: false
      matrix:
        lang: ${{ fromJson(needs.configure.outputs.linguas) }}

    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4

    - run: git config --global --replace-all safe.directory "$GITHUB_WORKSPACE"

    - name: Enable gettext stats problem matcher
      run: echo "::add-matcher::.github/problem-matchers/gettext-stats.json"

    - name: Enable generic problem matcher
      run: echo "::add-matcher::.github/problem-matchers/generic.json"

    - name: Compile translation
      run: make msgfmt/${{ matrix.lang }} 2>&1 | tee $GITHUB_STEP_SUMMARY
      shell: bash

    - name: Disable gettext stats problem matcher
      run: echo "::remove-matcher owner=gettext-stats::"

    - name: Ensure .po file is in sync with .pot
      run: |
        touch po/*.pot # Make sure .pot won't be re-generated
        make msgcmp/${{ matrix.lang }} 2>&1
      shell: bash
      if: ${{ always() && steps.checkout.conclusion == 'success' }}
