name: lint

on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/amezin/gnome-shell-pod-34:master

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - run: npm ci
    - run: make lint

  glib-compile-schemas:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/amezin/gnome-shell-pod-34:master

    steps:
    - uses: actions/checkout@v3
    - run: make schemas/gschemas.compiled

  gtk-builder-validate:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/amezin/gnome-shell-pod-34:master

    steps:
    - uses: actions/checkout@v3
    - run: xvfb-run make gtk-builder-validate
