on:
  workflow_call:
    inputs:
      artifact:
        description: 'Artifact name'
        default: 'shell-extension'
        required: false
        type: string
    outputs:
      artifact:
        description: 'Artifact name'
        value: ${{ jobs.pack.outputs.artifact }}

jobs:
  pack:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ddterm/ci-docker-image:master

    outputs:
      artifact: ${{ inputs.artifact }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - run: npm ci
    - run: xvfb-run make pack
    - id: upload
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.artifact }}
        path: "*.shell-extension.zip"
        if-no-files-found: error
